package ph.edu.dlsu.mobdeve.naval.gabrielle.stardewvalleyguide.dao

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import ph.edu.dlsu.mobdeve.naval.gabrielle.stardewvalleyguide.R

class FishDBHandler (context: Context): SQLiteOpenHelper(context, DBName, null, DBVersion) {
    companion object {
        private val DBVersion = 1
        private val DBName = "FishDatabase"

        //table name
        val TABLEFISH = "FishTable"

        val KEYID = "id"
        val KEYNAME = "name"
        val KEYSPRING = "spring"
        val KEYSUMMER = "summer"
        val KEYFALL = "fall"
        val KEYWINTER = "winter"
        val KEYFOUNDIN = "foundin"
        val KEYTIME = "time"
        val KEYWEATHER = "weather"
        val KEYSIZE = "size"
        val KEYHEAL = "heal"
        val KEYSELL = "sell"
        val KEYIMG = "img"

    }

    override fun onCreate(db: SQLiteDatabase?) {
        val CREATEFISHTABLE = "CREATE TABLE $TABLEFISH " +
                "($KEYID INTEGER PRIMARY KEY AUTOINCREMENT, " +
                "$KEYNAME TEXT, " +
                "$KEYSPRING INT, " +
                "$KEYSUMMER INT, " +
                "$KEYFALL INT, " +
                "$KEYWINTER INT, " +
                "$KEYFOUNDIN TEXT, " +
                "$KEYTIME TEXT, " +
                "$KEYWEATHER TEXT, " +
                "$KEYSIZE TEXT, " +
                "$KEYHEAL TEXT, " +
                "$KEYSELL TEXT, " +
                "$KEYIMG INT)"
        db!!.execSQL(CREATEFISHTABLE)

        with(ContentValues()) {
            put(KEYNAME, "Pufferfish")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean (All Seasons on Ginger Island)")
            put(KEYTIME, "12pm - 4pm")
            put(KEYWEATHER, "Sun")
            put(KEYSIZE, "1 - 37")
            put(KEYHEAL, "-100 Energy - -260 Energy")
            put(KEYSELL, "200g - 400g")
            put(KEYIMG, R.drawable.pufferfish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Anchovy")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "1 - 17")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "30g - 60g")
            put(KEYIMG, R.drawable.anchovy)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Tuna")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean (All Seasons on Ginger Island)")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 61")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.tuna)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Sardine")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "1 - 13")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "40g - 80g")
            put(KEYIMG, R.drawable.sardine)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Bream")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "River")
            put(KEYTIME, "6pm - 2am")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 31")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "45g - 90g")
            put(KEYIMG, R.drawable.bream)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Largemouth Bass")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mountain Lake & Wilderness Farm")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "11 - 31")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.largemouth_bass)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Smallmouth Bass")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Town River & Forest Pond")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 25")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "50g - 100g")
            put(KEYIMG, R.drawable.smallmouth_bass)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Rainbow Trout")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "River & Mountain Lake")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Sun")
            put(KEYSIZE, "10 - 26")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "65g - 130g")
            put(KEYIMG, R.drawable.rainbow_trout)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Salmon")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "River")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "24 - 66")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.salmon)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Walleye")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "River, Mountain Lake, Forest Pond & Forest Pond Farm")
            put(KEYTIME, "12pm - 2am")
            put(KEYWEATHER, "Rain (Winter with a Rain Token)")
            put(KEYSIZE, "10 - 41")
            put(KEYHEAL, "30 Energy - 78 Energy & 13 Health - 35 Health")
            put(KEYSELL, "105g - 210g")
            put(KEYIMG, R.drawable.walleye)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Perch")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "River, Mountain Lake & Forest Pond")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "10 - 25")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "55g - 110g")
            put(KEYIMG, R.drawable.perch)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Carp")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mountain Lake, Secret Woods, The Sewers & Mutant Bug Lair")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "15 - 51")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "30g - 60g")
            put(KEYIMG, R.drawable.carp)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Catfish")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "River, Secret Woods (Additionally Summer) & Witch's Swamp (Additionally Summer)")
            put(KEYTIME, "6am - 12am")
            put(KEYWEATHER, "Rain (Winter with Rain Totem)")
            put(KEYSIZE, "12 - 73")
            put(KEYHEAL, "50 Energy - 130 Energy & 22 Health - 58 Health")
            put(KEYSELL, "200g - 400g")
            put(KEYIMG, R.drawable.catfish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Pike")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "River & Forest Pond")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "15 - 61")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.pike)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Sunfish")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "River")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Sun & Wind")
            put(KEYSIZE, "5 - 16")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "30g - 60g")
            put(KEYIMG, R.drawable.sunfish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Red Mullet")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "8 - 23")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.red_mullet)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Herring")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 0)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "8 - 21")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "30g - 60g")
            put(KEYIMG, R.drawable.herring)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Eel")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "4pm - 2am")
            put(KEYWEATHER, "Rain")
            put(KEYSIZE, "12 - 81")
            put(KEYHEAL, "30 Energy - 78 Energy & 13 Health - 35 Health")
            put(KEYSELL, "85g - 170g")
            put(KEYIMG, R.drawable.eel)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Octopus")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean, Ginger Island & Submarine at Night Market (Winter)")
            put(KEYTIME, "6am - 1pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 49")
            put(KEYHEAL, "Inedible")
            put(KEYSELL, "150g - 300g")
            put(KEYIMG, R.drawable.octopus)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Red Snapper")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean & Beach Farm")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Rain (Winter with Rain Totem)")
            put(KEYSIZE, "8 - 26")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "50g - 100g")
            put(KEYIMG, R.drawable.red_snapper)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Squid")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "6pm - 2am")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 49")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "80g - 160g")
            put(KEYIMG, R.drawable.squid)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Sea Cucumber")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean & Submarine at Night Market")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "3 - 21")
            put(KEYHEAL, "-25 Energy - -65 Energy")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.sea_cucumber)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Super Cucumber")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean, Ginger Island (All Seasons) & Submarine at Night Market")
            put(KEYTIME, "6pm - 2am")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 37")
            put(KEYHEAL, "125 Energy - 325 Energy & 56 Health - 146 Health")
            put(KEYSELL, "250g - 500g")
            put(KEYIMG, R.drawable.super_cucumber)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Ghostfish")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "The Mines")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "10 - 36")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "45g - 90g")
            put(KEYIMG, R.drawable.ghostfish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Stonefish")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Level 20 of The Mines")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "14 - 16")
            put(KEYHEAL, "Inedible")
            put(KEYSELL, "300g - 600g")
            put(KEYIMG, R.drawable.stonefish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Ice Pip")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Level 60 of The Mines")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "7 - 9")
            put(KEYHEAL, "39 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "500g - 1000g")
            put(KEYIMG, R.drawable.ice_pip)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Lava Eel")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Level 100 of The Mines & Volcano Caldera")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "31 - 33")
            put(KEYHEAL, "50 Energy - 130 Energy & 22 Health - 58 Health")
            put(KEYSELL, "700g - 1400g")
            put(KEYIMG, R.drawable.lava_eel)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Sandfish")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "The Desert")
            put(KEYTIME, "6am - 8pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "8 - 25")
            put(KEYHEAL, "13 Energy - 33 Energy & 5 Health - 14 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.sandfish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Scorpion Carp")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "The Desert")
            put(KEYTIME, "6am - 8pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 33")
            put(KEYHEAL, "-125 Energy - -325 Energy")
            put(KEYSELL, "150g - 300g")
            put(KEYIMG, R.drawable.scorpion_carp)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Flounder")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean & Ginger Island (All Seasons)")
            put(KEYTIME, "6am - 8pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "4 - 17")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.flounder)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Midnight Carp")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mountain Lake, Forest Pond & Ginger Island North & West")
            put(KEYTIME, "10pm - 2am")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 53")
            put(KEYHEAL, "50 Energy - 130 Energy & 22 Health - 58 Health")
            put(KEYSELL, "150g - 300g")
            put(KEYIMG, R.drawable.midnight_carp)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Sturgeon")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mountain Lake")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 61")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "200g - 400g")
            put(KEYIMG, R.drawable.sturgeon)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Tiger Trout")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "River")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "10 - 21")
            put(KEYHEAL, "25 - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "150g - 300g")
            put(KEYIMG, R.drawable.tiger_trout)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Bullhead")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mountain Lake")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 31")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.bullhead)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Tilapia")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Ocean & Ginger Island (All Seasons)")
            put(KEYTIME, "6am - 2pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "11 - 31")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.tilapia)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Chub")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mountain Lake & Forest River")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "12 - 25")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "50g - 100g")
            put(KEYIMG, R.drawable.chub)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Dorado")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "Forest River")
            put(KEYTIME, "6am - 7pm")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "24 - 33")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.dorado)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Albacore")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "6am - 11am & 6pm - 2am")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "20 - 41")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.albacore)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Shad")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 0)
            put(KEYFOUNDIN, "River")
            put(KEYTIME, "9am - 2am")
            put(KEYWEATHER, "Rain")
            put(KEYSIZE, "20 - 49")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "60g - 120g")
            put(KEYIMG, R.drawable.shad)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Lingcod")
            put(KEYSPRING, 0)
            put(KEYSUMMER, 0)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "River & Mountain Lake")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "30 - 51")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "120g - 240g")
            put(KEYIMG, R.drawable.lingcod)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Halibut")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 0)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ocean")
            put(KEYTIME, "6am - 11am & 7pm - 2am")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "10 - 34")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "80g - 160g")
            put(KEYIMG, R.drawable.halibut)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Woodskip")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Secret Woods & Forest Farm")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "11 - 31")
            put(KEYHEAL, "25 Energy - 65 Energy & 11 Health - 29 Health")
            put(KEYSELL, "75g - 150g")
            put(KEYIMG, R.drawable.woodskip)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Void Salmon")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Withc's Swamp")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "24 - 66")
            put(KEYHEAL, "63 Energy - 163 Energy & 28 Health - 73 Health")
            put(KEYSELL, "150g - 300g")
            put(KEYIMG, R.drawable.void_salmon)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Slimejack")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Mutant Bug Lair")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "8 - 26")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.slimejack)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Stingray")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Pirate Cove")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "18 - 61")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "180g - 360g")
            put(KEYIMG, R.drawable.stingray)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Lionfish")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ginger Island")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "3 - 13")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "100g - 200g")
            put(KEYIMG, R.drawable.lionfish)
            db.insert(TABLEFISH, null, this)

            put(KEYNAME, "Blue Discus")
            put(KEYSPRING, 1)
            put(KEYSUMMER, 1)
            put(KEYFALL, 1)
            put(KEYWINTER, 1)
            put(KEYFOUNDIN, "Ginger Island")
            put(KEYTIME, "Any")
            put(KEYWEATHER, "Any")
            put(KEYSIZE, "2 - 10")
            put(KEYHEAL, "38 Energy - 98 Energy & 17 Health - 44 Health")
            put(KEYSELL, "120g - 240g")
            put(KEYIMG, R.drawable.blue_discus)
            db.insert(TABLEFISH, null, this)
        }
    }

    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        db!!.execSQL("DROP TABLE IF EXISTS " + TABLEFISH)
        onCreate(db)
    }
}